server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  h2:
    console:
      path: /h2
      enabled: true
graphql:
  servlet:
    mapping: /graphql/*
    enabled: true
    corsEnabled: true
    subscriptions:
      websocket:
        path: /subscriptions
      apollo:
        keep-alive-enabled: true
        keep-alive-interval-seconds: 300000000
    async-mode-enabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: GraphiQL


---
# development profile
h2:
  console:
    path: /h2
    enabled: true
